DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE GENRES(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE AUTHORS(
    ID BIGINT PRIMARY KEY,
    SURNAME VARCHAR(255),
    NAME VARCHAR(255)
);

CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);